//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int idMail { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<int> idModulo { get; set; }
        public Nullable<int> idTarea { get; set; }
        public string asunto { get; set; }
        public string detalle { get; set; }
        public string destinatarios { get; set; }
        public string enviado { get; set; }
    }
}
