//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public Modulos()
        {
            this.Tareas = new HashSet<Tareas>();
        }
    
        public int idModulo { get; set; }
        public int idProyecto { get; set; }
        public int idUsuarioCreador { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Tareas> Tareas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
