//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantesProyectos
    {
        public int idUsuario { get; set; }
        public int idProyecto { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
    }
}
