//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public Tareas()
        {
            this.ParticipantesTareas = new HashSet<ParticipantesTareas>();
        }
    
        public int idTarea { get; set; }
        public int idModulo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public string AlertaPrevia { get; set; }
        public string DireccionGPS { get; set; }
        public string Prioridad { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
        public Nullable<double> Tiempo { get; set; }
        public int Baja { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual ICollection<ParticipantesTareas> ParticipantesTareas { get; set; }
    }
}
