//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Participantes = new HashSet<Participantes>();
            this.Modulos = new HashSet<Modulos>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public bool usuarioActivo { get; set; }
        public string codigoVerificacion { get; set; }
    
        public virtual ICollection<Participantes> Participantes { get; set; }
        public virtual ICollection<Modulos> Modulos { get; set; }
    }
}
